# Generated by Django 5.2.4 on 2026-01-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
    ]
