# Generated by Django 5.2.4 on 2026-01-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_alter_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
    ]
